version: '2'
services:
  cascadeservices-app:
    image: cascadeservices
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://cascadeservices-mssql:1433;database=CascadeServices
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://cascadeservices-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://cascadeservices-elasticsearch:9200
    ports:
      - 8080:8080
  cascadeservices-mssql:
    extends:
      file: mssql.yml
      service: cascadeservices-mssql
  cascadeservices-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: cascadeservices-elasticsearch
